name: GitHub Profile Summary Cards

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch: {}
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ secrets.CLI_ID }}
          private-key: ${{ secrets.CLI_PRV }}
      - uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: ${{ github.repository_owner }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
